default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ultrarend_development

test:
  adapter: sqlite3
  database: ultrarend_test
  timeout: 5000

production:
  <<: *default
  database: ultrarend_production
  username: ultrarend
  password: <%= ENV['ULTRAREND_DATABASE_PASSWORD'] %>
